### ISSUE TITLE
## Change

### ISSUE THREAD

**Issue by Anastasia1510** [Uniswap/token-lists#154]
## Change
added a rich mode for more convenient local contract testing. In this mode gas params will default to large amount so all operations should not require at gas overrides anymore.

This is especially helpful for large contract tests with hardhat.

## Test
Tested some local contract deployments without gas overrides:
- when rich mode is enabled, contract creation succeed
- when rich mode disabled, contract creation will fail by `Error: evm.OutOfStorage: Storage usage exceeds storage limit`

__Originally posted by @shunjizhan in https://github.com/AcalaNetwork/bodhi.js/pull/511__

__Originally posted by @Anastasia1510 in https://github.com/Anastasia1510/-/issues/1__

**Comment by alfiomy** [comment]
0x6208ebbF4dcB27b3368a79066d8e0d25Aa471607
