### ISSUE TITLE
Coingecko Token List [replace DeFi 100]

### ISSUE THREAD

**Issue by TModMarco** [Uniswap/token-lists#17]
Hoping this is the right place to share this, wasn't sure if it should be here or in the other token-list section.

A great suggestion by the Coingecko founder on the Uniswap Governance Forum, which I believe belongs here. As it's more a 'replace with' than a 'vote to have Coingecko listed to the default list' situation.

https://gov.uniswap.org/t/add-the-coingecko-tokens-list-in-the-manage-lists-section/6205

Currently Uniswap offers the 'Coingecko DeFi 100' list. However, I quote:
''I would like to propose to have that CoinGecko tokens list to be in the default “Manage List” section replacing the CoinGecko DeFi 100 for the following reasons:-

- CoinGecko tokens list updates every hour with all the latest updates/changes (new tokens, contract address change, etc…)
- CoinGecko DeFi 100 list was our first attempt, and we noticed that a list with all tokens is a better user experience as Uniswap traders don’t have to switch in/out to find the address they are looking for
- We did not implement DeFi 100 in the best way; which makes it difficult for us to get it updated with any changes in token details in our backend, and we should deprecate it''

''by making it easier for general Uniswap users to access the CoinGecko token lists

- Users will get the latest changes to the token as timely as possible (contract address, decimals, any metadata related) in order to trade the correct token
- Users get to find all the tokens that are curated on CoinGecko.com
- Users can look up in the list using symbols''

Kind Regards,
TMod_Marco

**Comment by moodysalem** [comment]
Default list of lists can be modified here
https://github.com/Uniswap/uniswap-interface/blob/master/src/constants/lists.ts#L4

Hypothetically, additional work could be done on the interface to load this list of lists from ENS, allowing governance to modify the list of lists. However, a proposal to modify the list of lists does not need to be made at this time--simply send a PR to replace the existing Coingecko list with the desired one.
