### ISSUE TITLE
AJV - Error: unknown format "date-time" ignored in schema at path "#/properties/timestamp"

### ISSUE THREAD

**Issue by Gazoh** [Uniswap/token-lists#19]
So i want to make my own list. I've created a react project to start with. This is the function i made to validate a list.

` const generateMyTokenList = (tokenList: TokenList) => {
        // Your list
        const myList = tokenList;
        // Creating a new Ajv object
        const validator = new Ajv();
        // Validating if the scheme is a valid scheme
        const validateScheme = validator.validateSchema(schema);
        // If the validateScheme returns true it is a valid scheme than validate my list
        if(validateScheme) {
            let validatedList = validator.validate(schema, myList); 
        }
    }`

whenever i pass my list to the function it validates the list and it works. But it gives me back 2 errors:
"Error: unknown format "date-time" ignored in schema at path "#/properties/timestamp" **AND**
"Error: unknown format "uri" ignored in schema at path "#/properties/logoURI". 

Everything that takes the parameter: **format** gives me an error back. And whenever i take that json scheme and remove the 'formats' it will no longer return errors. So am i doing something wrong or is there something wrong? 

This is the list i am using: [https://github.com/Uniswap/token-lists/blob/master/test/schema/example.tokenlist.json](https://github.com/Uniswap/token-lists/blob/master/test/schema/example.tokenlist.json)

**Comment by moodysalem** [comment]
Check the version of your ajv, these are part of the json schema spec. Not an issue with token-lists. 
https://json-schema.org/understanding-json-schema/reference/string.html#built-in-formats
