### ISSUE TITLE
Add Conditional Tokens List to tokenlists.org

### ISSUE THREAD

**Issue by auryn-macmillan** [Uniswap/token-lists#23]
The [Conditional Tokens Framework](https://github.com/gnosis/conditional-tokens-contracts) is the underlying technology that prediction markets like [Omen](https://omen.eth.link) and [Polymarket](https://poly.market) are built on. They are ERC1155 tokens, but we have deployed an [ERC20 wrapper](https://github.com/gnosis/1155-to-20) so that they can be used with contracts and applications that support ERC20 but do not support ERC1155.

One feature of the ERC20 wrapper is that the `name` and `symbol` of each token is identical ("wrapped multi token" and WMT), this is to make it more generally useful.

To remedy this, we have started curating a list of wrapped conditional tokens and would like to add it to the default list at tokenlists.org.

The list can be found here:
`https://github.com/gnosis/conditional-tokens-list/blob/main/conditional-token-list.json`

**Comment by Lukasz257** [comment]
https://github.com/Uniswap/token-lists/issues/23#issue-comment-box

**Comment by NoahZinsmeister** [comment]
hi @auryn-macmillan , please open this issue on https://github.com/Uniswap/tokenlists-org
