### ISSUE TITLE
Ca$htaker

### ISSUE THREAD

**Issue by Crist523** [Uniswap/token-lists#317]

**Comment by Sissi39** [comment]
Je réussi jamais


-------- Message d'origine --------
De : Crist523 ***@***.***>
Date : 23-04-10 3 h 37 a.m. (GMT-05:00)
À : Uniswap/token-lists ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [Uniswap/token-lists] Ca$htaker (Issue #317)
