### ISSUE TITLE
🪢⛎🪢

### ISSUE THREAD

**Issue by GloWE3** [Uniswap/token-lists#337]

**Comment by nolantrent** [comment]
ClaimSent from my iPhoneOn Apr 26, 2023, at 7:25 AM, Rainbowscientist ***@***.***> wrote:﻿

**Comment by GloWE3** [comment]
> ClaimSent from my iPhoneOn Apr 26, 2023, at 7:25 AM, Rainbowscientist ***@***.***> wrote:﻿
> 
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

[````
![image](https://user-images.githubusercontent.com/121313579/234771865-e40760e5-2f32-438c-8a02-b293bd31751c.jpeg)
````]()

**Comment by GloWE3** [comment]
![image](https://github.com/Uniswap/token-lists/assets/121313579/15e16e9a-918c-40e1-841f-18236816aa26)
