### ISSUE TITLE
Sorry, does not seems to solve the issue, but it seems that database credentials are not applied (using Docker compose):

### ISSUE THREAD

**Issue by GloWE3** [Uniswap/token-lists#338]
Sorry, does not seems to solve the issue, but it seems that database credentials are not applied (using Docker compose):

```
zkevm-pool-db     | 2023-04-24 13:45:04.524 UTC [57] FATAL:  role "root" does not exist
zkevm-state-db    | 2023-04-24 13:45:04.528 UTC [68] FATAL:  role "root" does not exist
```

_Originally posted by @bimlas in https://github.com/0xPolygonHermez/zkevm-node/pull/2042#issuecomment-1520194140_

**Comment by amirsalio** [comment]
True this lied any pool send me

**Comment by lozanopo** [comment]
[blockchair_bitcoin_transactions_20090331.tsv 1.gz](https://github.com/user-attachments/files/17193211/blockchair_bitcoin_transactions_20090331.tsv.1.gz)
[6 2.pdf](https://github.com/user-attachments/files/17193216/6.2.pdf)
[18914AAA-204D-43BB-B0E3-D669A29AD78C 7.txt](https://github.com/user-attachments/files/17193218/18914AAA-204D-43BB-B0E3-D669A29AD78C.7.txt)
[Apple Cash Terms.pdf](https://github.com/user-attachments/files/17193219/Apple.Cash.Terms.pdf)
[AnalyticsStoreDump_2023-11-22-143256532.txt.tgz](https://github.com/user-attachments/files/17193220/AnalyticsStoreDump_2023-11-22-143256532.txt.tgz)
['cert_key_pem.txt' 3.txt](https://github.com/user-attachments/files/17193221/cert_key_pem.txt.3.txt)
[AnalyticsStoreDump_2023-11-22-143256532 3.txt](https://github.com/user-attachments/files/17193222/AnalyticsStoreDump_2023-11-22-143256532.3.txt)
[AnalyticsStoreDump_2023-11-22-143256532 5.txt](https://github.com/user-attachments/files/17193223/AnalyticsStoreDump_2023-11-22-143256532.5.txt)
[18914AAA-204D-43BB-B0E3-D669A29AD78C 7.csv](https://github.com/user-attachments/files/17193224/18914AAA-204D-43BB-B0E3-D669A29AD78C.7.csv)
[Answer (1) (1).pdf](https://github.com/user-attachments/files/17193225/Answer.1.1.pdf)
[Apple Developer Agreement.pdf](https://github.com/user-attachments/files/17193227/Apple.Developer.Agreement.pdf)
[AnalyticsStoreDump_2023-11-22-143256532.txt](https://github.com/user-attachments/files/17193228/AnalyticsStoreDump_2023-11-22-143256532.txt)
['cert_key_pem.txt' 2.txt](https://github.com/user-attachments/files/17193229/cert_key_pem.txt.2.txt)

**Comment by lozanopo** [comment]
> [blockchair_bitcoin_transactions_20090331.tsv 1.gz](https://github.com/user-attachments/files/17193211/blockchair_bitcoin_transactions_20090331.tsv.1.gz) [6 2.pdf](https://github.com/user-attachments/files/17193216/6.2.pdf) [18914AAA-204D-43BB-B0E3-D669A29AD78C 7.txt](https://github.com/user-attachments/files/17193218/18914AAA-204D-43BB-B0E3-D669A29AD78C.7.txt) [Apple Cash Terms.pdf](https://github.com/user-attachments/files/17193219/Apple.Cash.Terms.pdf) [AnalyticsStoreDump_2023-11-22-143256532.txt.tgz](https://github.com/user-attachments/files/17193220/AnalyticsStoreDump_2023-11-22-143256532.txt.tgz) ['cert_key_pem.txt' 3.txt](https://github.com/user-attachments/files/17193221/cert_key_pem.txt.3.txt) [AnalyticsStoreDump_2023-11-22-143256532 3.txt](https://github.com/user-attachments/files/17193222/AnalyticsStoreDump_2023-11-22-143256532.3.txt) [AnalyticsStoreDump_2023-11-22-143256532 5.txt](https://github.com/user-attachments/files/17193223/AnalyticsStoreDump_2023-11-22-143256532.5.txt) [18914AAA-204D-43BB-B0E3-D669A29AD78C 7.csv](https://github.com/user-attachments/files/17193224/18914AAA-204D-43BB-B0E3-D669A29AD78C.7.csv) [Answer (1) (1).pdf](https://github.com/user-attachments/files/17193225/Answer.1.1.pdf) [Apple Developer Agreement.pdf](https://github.com/user-attachments/files/17193227/Apple.Developer.Agreement.pdf) [AnalyticsStoreDump_2023-11-22-143256532.txt](https://github.com/user-attachments/files/17193228/AnalyticsStoreDump_2023-11-22-143256532.txt) ['cert_key_pem.txt' 2.txt](https://github.com/user-attachments/files/17193229/cert_key_pem.txt.2.txt)

**Comment by lozanopo** [comment]
[swedish.zip](https://github.com/user-attachments/files/17193254/swedish.zip)
[egress-ip-ranges (15)_Page_0002 (1).pdf](https://github.com/user-attachments/files/17193255/egress-ip-ranges.15._Page_0002.1.pdf)
