### ISSUE TITLE
Duplicated line in Token list

### ISSUE THREAD

**Issue by johnkcr** [Uniswap/token-lists#44]
**Bug Description**
https://tokens.coingecko.com/all.json
There are duplicates lines in this list.

**Steps to Reproduce**
Here is the duplicated line info.
{"chainId":1,"address":"0xed0d5747a9ab03a75fbfec3228cd55848245b75d","name":"e Money","symbol":"NGM","decimals":6,"logoURI":"https://assets.coingecko.com/coins/images/13722/thumb/nx5m_kZJt3oz9UM0XhE-IEeJ8TGjX1831iNfLVWeMvHuYoyDGwN0vh9Wj8u5hCxe1u5Kw56zT5kqX_ia5u1hsMElA-ioKCvK2jUK4EdJMDUx4J1GOnjqIu30iXHrLfmdzqO2SyucZZZnutFVLIAkxWMcTbIo1GDPZ3dZSj2onSeEOnIY4GJKR9B6ByR1XUZrJxtpY9QjwoWLfPC.jpg?1611182880"}

**Expected Behavior**
It should be unique token list.

**Comment by Zedxioncryptocurrency** [comment]
"name": "ZEDXION Token",
    "website": "https://zedxion.io",
    "description": "ZEDXION is a stablecoin issued by Paxos in partnership with Etherum.",
    "explorer": "https://etherscan.io/token/0xfbc4f3f645c4003a2e4f4e9b51077d2daa9a9341,
    "type": "TRC20",
    "symbol": "ZEDXION",
    "decimals": 18,
    "status": "active",
    "id": "0xfbc4f3f645c4003a2e4f4e9b51077d2daa9a9341"
}

**Comment by moodysalem** [comment]
This is an issue with the list, not the spec
