### ISSUE TITLE
SyntaxError: Invalid regular expression: /^[ \w.'+\-%/À-ÖØ-öø-ÿ\:]+$/: Invalid escape

### ISSUE THREAD

**Issue by 0xEther** [Uniswap/token-lists#52]
The following line is throwing the error `SyntaxError: Invalid regular expression: /^[ \w.'+\-%/À-ÖØ-öø-ÿ\:]+$/: Invalid escape`:

https://github.com/Uniswap/token-lists/blob/b5865fbded944da8715e65fa2f3286efc6c18f87/src/tokenlist.schema.json#L170

These are the package versions I'm using:

```
"@uniswap/token-lists": "^1.0.0-beta.24",
"ajv": "^7.2.4",
"ajv-formats": "^1.6.1",
```

This is the validation script:

```
const ajv = new AJV();
addFormats(ajv);
const validate = ajv.compile(schema);
const valid = validate(tokenList); // a valid tokenList json
```

Using node v14.17.1

**Comment by moodysalem** [comment]
it looks like the forward slash needs to be escaped

**Comment by moodysalem** [comment]
I think it was the forward slash not being escaped, and the colon `:` being escaped
