### ISSUE TITLE
This is what my 2022 looked like on @ProductHunt. Get your #ProductHuntRewind2022 now! https://www.producthunt.com/rewind

### ISSUE THREAD

**Issue by cyny39** [Uniswap/token-lists#565]
This is what my 2022 looked like on @ProductHunt. Get your #ProductHuntRewind2022 now! https://www.producthunt.com/rewind![image.png](https://github.com/Uniswap/token-lists/assets/128437481/d22a17e3-96e2-40eb-bc0d-7a7fb788a0ce)@

**Comment by faysal00009** [comment]
https://www.producthunt.com/rewind![image.png](https://github.com/Uniswap/token-lists/assets/128437481/d22a17e3-96e2-40eb-bc0d-7a7fb788a0ce)@

**Comment by faysal00009** [comment]
https://www.producthunt.com/rewind![image.png](https://github.com/Uniswap/token-lists/assets/128437481/d22a17e3-96e2-40eb-bc0d-7a7fb788a0ce)@
