### ISSUE TITLE
Tokenlist schema is missing

### ISSUE THREAD

**Issue by icinsight** [Uniswap/token-lists#89]
The JSON schema ID is https://uniswap.org/tokenlist.schema.json => gives 
![image](https://user-images.githubusercontent.com/39129866/144348553-5e019a6b-6d36-4c36-832d-8d80032e7a30.png)

**Comment by Anna45W** [comment]
Eror😭

**Comment by icinsight** [comment]
Seems to be back online. Closing the issue.
