### ISSUE TITLE
List validation does not capture duplicates

### ISSUE THREAD

**Issue by icinsight** [Uniswap/token-lists#93]
If you have a duplicate entry in your list, it won't work on some UI's.

SushiSwap seems to be immune to that, but QuickSwap will not show the list, etc. I haven't tested all forks!

Anyway, I have added a script in my validation routine that checks dupilicate symbols and addresses.

I use my DYI Python script so I can't really post my 'fix' to this repo, but you get the idea.

**Comment by moodysalem** [comment]
Unfortunately there's not a way around this with JSON schemas

Even if we could force the addresses to be unique, we can't guarantee the addresses are checksummed, and can't validate on unique _lowercased_ addresses

Open to ideas for improving this though

**Comment by icinsight** [comment]
I use a python script that checks the duplicate issue after overall validation.

https://github.com/BlockTimeWorld/SwapMatic/blob/master/tokenlist_validation.py

**Comment by icinsight** [comment]
This can be closed now.
